steps:
# Step 1: Install mkdocs and other requirements
- name: 'python:3.11-slim'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      apt-get update && apt-get install -y zip  # Install zip utility
      python -m venv venv
      source venv/bin/activate
      pip install --upgrade pip
      pip install mkdocs mkdocs-material  # Add other requirements as needed
      if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

# Step 2: Build the documentation
- name: 'python:3.11-slim'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      source venv/bin/activate
      mkdocs build

# Step 3: Compress the documentation files into a .zip archive
- name: 'python:3.11-slim'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      apt-get update && apt-get install -y zip  # Ensure zip is installed
      zip -r site.zip site

# Step 4: Upload the documentation files to the bucket
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
    - 'gsutil'
    - '-m'
    - 'rsync'
    - '-r'
    - 'site'
    - 'gs://docs.octopwn.com/'

# Step 5: Upload the .zip file to the same bucket
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
    - 'gsutil'
    - 'cp'
    - 'site.zip'
    - 'gs://docs.octopwn.com/site.zip'

# Define the timeout for the build
timeout: '1200s'

# Define the logging options
options:
  logging: CLOUD_LOGGING_ONLY
